namespace SkyLIS.Domain.Common;

/// <summary>Base class for entities identified by a Guid (UUID v7 generated by the caller/factory).</summary>
public abstract class Entity
{
    public Guid Id { get; protected set; }

    protected Entity() { }

    protected Entity(Guid id)
    {
        if (id == Guid.Empty) throw new DomainException("Entity id cannot be empty.");
        Id = id;
    }

    public override bool Equals(object? obj) =>
        obj is Entity other && GetType() == other.GetType() && Id == other.Id;

    public override int GetHashCode() => HashCode.Combine(GetType(), Id);
}
