// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyLIS.Infrastructure.Persistence;

#nullable disable

namespace SkyLIS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SkyLisDbContext))]
    [Migration("20260816080537_PanelsAndAddOns")]
    partial class PanelsAndAddOns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyLIS.Domain.Billing.CashierShift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<decimal?>("DeclaredCash")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("declared_cash");

                    b.Property<decimal?>("ExpectedCash")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("expected_cash");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<Guid?>("OpenedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("Variance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("variance");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cashier_shifts");

                    b.HasIndex("TenantId", "BranchId", "Status")
                        .HasDatabaseName("ix_cashier_shifts_tenant_id_branch_id_status");

                    b.ToTable("cashier_shifts", "billing");
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CreditNoteNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("credit_note_number");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_credit_notes");

                    b.HasIndex("TenantId", "CreditNoteNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_notes_tenant_id_credit_note_number");

                    b.HasIndex("TenantId", "InvoiceId")
                        .HasDatabaseName("ix_credit_notes_tenant_id_invoice_id");

                    b.ToTable("credit_notes", "billing");
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<decimal>("CreditedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("credited_amount");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_amount");

                    b.Property<string>("DiscountReason")
                        .HasColumnType("text")
                        .HasColumnName("discount_reason");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("TenantId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_tenant_id_invoice_number");

                    b.HasIndex("TenantId", "VisitId")
                        .HasDatabaseName("ix_invoices_tenant_id_visit_id");

                    b.ToTable("invoices", "billing");
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refund");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("invoice_id")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("invoice_id")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.ToTable("payments", "billing");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.LabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<Guid?>("RequiredConditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_condition_id");

                    b.Property<Guid>("SampleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_lab_tests");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_tests_tenant_id_code");

                    b.ToTable("lab_tests", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_panels");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_panels_tenant_id_code");

                    b.ToTable("panels", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.PanelItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uuid")
                        .HasColumnName("panel_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("pk_panel_items");

                    b.HasIndex("PanelId")
                        .HasDatabaseName("ix_panel_items_panel_id");

                    b.HasIndex("TenantId", "PanelId", "TestId")
                        .IsUnique()
                        .HasDatabaseName("ix_panel_items_tenant_id_panel_id_test_id");

                    b.ToTable("panel_items", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompatibilityGroup")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("compatibility_group");

                    b.Property<int?>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("SampleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_type_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sample_conditions");

                    b.HasIndex("SampleTypeId")
                        .HasDatabaseName("ix_sample_conditions_sample_type_id");

                    b.ToTable("sample_conditions", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sample_types");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sample_types_tenant_id_name");

                    b.ToTable("sample_types", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Files.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_name");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_attachments_tenant_id_entity_type_entity_id");

                    b.ToTable("attachments", "files");
                });

            modelBuilder.Entity("SkyLIS.Domain.Org.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_tenant_id_code");

                    b.ToTable("branches", "org");
                });

            modelBuilder.Entity("SkyLIS.Domain.Org.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_branch_departments");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_branch_departments_branch_id");

                    b.HasIndex("TenantId", "BranchId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_branch_departments_tenant_id_branch_id_code");

                    b.ToTable("branch_departments", "org");
                });

            modelBuilder.Entity("SkyLIS.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confidential");

                    b.Property<DateTimeOffset?>("LastVisitAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_at_utc");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("NationalId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("national_id");

                    b.Property<string>("PatientNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("patient_number");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("TenantId", "FullName")
                        .HasDatabaseName("ix_patients_tenant_id_full_name");

                    b.HasIndex("TenantId", "Mobile")
                        .HasDatabaseName("ix_patients_tenant_id_mobile");

                    b.HasIndex("TenantId", "NationalId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_tenant_id_national_id")
                        .HasFilter("national_id IS NOT NULL");

                    b.HasIndex("TenantId", "PatientNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_tenant_id_patient_number");

                    b.ToTable("patients", "patients");
                });

            modelBuilder.Entity("SkyLIS.Domain.Platform.CountryPack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("SampleTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_types");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_country_packs");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_country_packs_country_code");

                    b.ToTable("country_packs", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Platform.MasterTest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("ConditionName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("condition_name");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("department");

                    b.Property<DateTimeOffset?>("LastPushedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_pushed_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PushCount")
                        .HasColumnType("integer")
                        .HasColumnName("push_count");

                    b.Property<string>("SampleTypeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sample_type_name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_master_tests");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_master_tests_code");

                    b.ToTable("master_tests", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Platform.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("max_branches");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_users");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monthly_price");

                    b.Property<int>("MonthlyReportQuota")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_report_quota");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_code");

                    b.ToTable("plans", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Reports.LabReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_html");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kind");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RenderedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rendered_at_utc");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("report_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_lab_reports");

                    b.HasIndex("TenantId", "VisitId")
                        .HasDatabaseName("ix_lab_reports_tenant_id_visit_id");

                    b.HasIndex("TenantId", "ReportNumber", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_reports_tenant_id_report_number_version");

                    b.ToTable("lab_reports", "reports");
                });

            modelBuilder.Entity("SkyLIS.Domain.Reports.ReportDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at_utc");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_report_deliveries");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_deliveries_report_id");

                    b.ToTable("report_deliveries", "reports");
                });

            modelBuilder.Entity("SkyLIS.Domain.Reports.ReportVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer_name");

                    b.Property<string>("PatientInitials")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("patient_initials");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("report_number");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_report_verifications");

                    b.ToTable("report_verifications", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Results.CriticalNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalledPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("called_person");

                    b.Property<string>("CalledPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("called_phone");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("FlaggedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flagged_at_utc");

                    b.Property<bool>("ReadBackConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("read_back_confirmed");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TestResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_result_id");

                    b.HasKey("Id")
                        .HasName("pk_critical_notifications");

                    b.HasIndex("TestResultId")
                        .IsUnique()
                        .HasDatabaseName("ix_critical_notifications_test_result_id");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("ix_critical_notifications_tenant_id_state");

                    b.ToTable("critical_notifications", "results");
                });

            modelBuilder.Entity("SkyLIS.Domain.Results.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AmendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("amended_at_utc");

                    b.Property<Guid?>("AmendedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("amended_by_user_id");

                    b.Property<string>("AmendmentReason")
                        .HasColumnType("text")
                        .HasColumnName("amendment_reason");

                    b.Property<bool>("DeltaFlagged")
                        .HasColumnType("boolean")
                        .HasColumnName("delta_flagged");

                    b.Property<DateTimeOffset>("EnteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at_utc");

                    b.Property<Guid>("EnteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by_user_id");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("flag");

                    b.Property<string>("InterpretiveComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("interpretive_comment");

                    b.Property<bool>("IsAmended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_amended");

                    b.Property<DateTimeOffset?>("MedicallyValidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("medically_validated_at_utc");

                    b.Property<Guid?>("MedicallyValidatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("medically_validated_by");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<decimal?>("PreviousValue")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("previous_value");

                    b.Property<string>("RerunReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rerun_reason");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signature_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TechnicallyValidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("technically_validated_at_utc");

                    b.Property<Guid?>("TechnicallyValidatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("technically_validated_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("test_code");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("value");

                    b.Property<decimal?>("ValueBeforeAmendment")
                        .HasColumnType("numeric")
                        .HasColumnName("value_before_amendment");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<Guid>("VisitTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_test_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_test_results");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_test_results_tenant_id_status");

                    b.HasIndex("TenantId", "VisitTestId")
                        .HasDatabaseName("ix_test_results_tenant_id_visit_test_id");

                    b.HasIndex("TenantId", "PatientId", "TestCode")
                        .HasDatabaseName("ix_test_results_tenant_id_patient_id_test_code");

                    b.ToTable("test_results", "results");
                });

            modelBuilder.Entity("SkyLIS.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IsolationTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("isolation_tier");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("subdomain");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_subdomain");

                    b.ToTable("tenants", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("user_name");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("roles");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_user_name");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset?>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at_utc");

                    b.Property<bool>("ConditionDelayed")
                        .HasColumnType("boolean")
                        .HasColumnName("condition_delayed");

                    b.Property<string>("ConditionName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("condition_name");

                    b.Property<DateTimeOffset?>("ConditionReadyAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("condition_ready_at_utc");

                    b.Property<DateTimeOffset?>("PatientInformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("patient_informed_at_utc");

                    b.Property<DateTimeOffset?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("rejection_reason_code");

                    b.Property<Guid>("SampleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_type_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_samples");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_samples_visit_id");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_samples_tenant_id_barcode");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("ix_samples_tenant_id_state");

                    b.ToTable("samples", "visits");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<bool>("IsStat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stat");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("StatReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stat_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VisitNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("visit_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_visits_tenant_id_status");

                    b.HasIndex("TenantId", "VisitNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_visits_tenant_id_visit_number");

                    b.ToTable("visits", "visits");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.VisitTest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("test_code");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid?>("visit_id")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_tests");

                    b.HasIndex("visit_id")
                        .HasDatabaseName("ix_visit_tests_visit_id");

                    b.ToTable("visit_tests", "visits");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_tenant_id_occurred_at_utc");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_events_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_events", "audit");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Metering.UsageMeter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("FinalizedReports")
                        .HasColumnType("integer")
                        .HasColumnName("finalized_reports");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_usage_meters");

                    b.HasIndex("TenantId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_usage_meters_tenant_id_year_month");

                    b.ToTable("usage_meters", "platform");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Outbox.InboxConsumption", b =>
                {
                    b.Property<string>("HandlerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler_name");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("HandlerName", "EventId")
                        .HasName("pk_inbox_consumptions");

                    b.ToTable("inbox_consumptions", "outbox");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "outbox");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Persistence.NumberSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_number_series");

                    b.HasIndex("TenantId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_number_series_tenant_id_kind");

                    b.ToTable("number_series", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.CashierShift", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "OpeningFloat", b1 =>
                        {
                            b1.Property<Guid>("CashierShiftId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("opening_float");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("CashierShiftId");

                            b1.ToTable("cashier_shifts", "billing");

                            b1.WithOwner()
                                .HasForeignKey("CashierShiftId")
                                .HasConstraintName("fk_cashier_shifts_cashier_shifts_id");
                        });

                    b.Navigation("OpeningFloat")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.CreditNote", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CreditNoteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("CreditNoteId");

                            b1.ToTable("credit_notes", "billing");

                            b1.WithOwner()
                                .HasForeignKey("CreditNoteId")
                                .HasConstraintName("fk_credit_notes_credit_notes_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Invoice", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_currency");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("invoices", "billing");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_invoices_invoices_id");
                        });

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Payment", b =>
                {
                    b.HasOne("SkyLIS.Domain.Billing.Invoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("invoice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments", "billing");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId")
                                .HasConstraintName("fk_payments_payments_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.LabTest", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("LabTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("LabTestId");

                            b1.ToTable("lab_tests", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("LabTestId")
                                .HasConstraintName("fk_lab_tests_lab_tests_id");
                        });

                    b.OwnsOne("SkyLIS.Domain.Catalog.ResultSchema", "ResultSchema", b1 =>
                        {
                            b1.Property<Guid>("LabTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("AbsurdHigh")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("absurd_high");

                            b1.Property<decimal?>("AbsurdLow")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("absurd_low");

                            b1.Property<bool>("AutoVerify")
                                .HasColumnType("boolean")
                                .HasColumnName("auto_verify");

                            b1.Property<decimal?>("CriticalHigh")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("critical_high");

                            b1.Property<decimal?>("CriticalLow")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("critical_low");

                            b1.Property<decimal?>("DeltaThresholdPercent")
                                .HasPrecision(7, 2)
                                .HasColumnType("numeric(7,2)")
                                .HasColumnName("delta_threshold_percent");

                            b1.Property<decimal?>("RefHigh")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("ref_high");

                            b1.Property<decimal?>("RefLow")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("ref_low");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("result_unit");

                            b1.HasKey("LabTestId");

                            b1.ToTable("lab_tests", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("LabTestId")
                                .HasConstraintName("fk_lab_tests_lab_tests_id");
                        });

                    b.Navigation("Price");

                    b.Navigation("ResultSchema");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.Panel", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("PanelId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("PanelId");

                            b1.ToTable("panels", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("PanelId")
                                .HasConstraintName("fk_panels_panels_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.PanelItem", b =>
                {
                    b.HasOne("SkyLIS.Domain.Catalog.Panel", null)
                        .WithMany("Items")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_panel_items_panels_panel_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleCondition", b =>
                {
                    b.HasOne("SkyLIS.Domain.Catalog.SampleType", null)
                        .WithMany("Conditions")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sample_conditions_sample_types_sample_type_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Org.Department", b =>
                {
                    b.HasOne("SkyLIS.Domain.Org.Branch", null)
                        .WithMany("Departments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branch_departments_branches_branch_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Reports.ReportDelivery", b =>
                {
                    b.HasOne("SkyLIS.Domain.Reports.LabReport", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_deliveries_lab_reports_report_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Results.CriticalNotification", b =>
                {
                    b.HasOne("SkyLIS.Domain.Results.TestResult", null)
                        .WithOne("Critical")
                        .HasForeignKey("SkyLIS.Domain.Results.CriticalNotification", "TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_critical_notifications_test_results_test_result_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Sample", b =>
                {
                    b.HasOne("SkyLIS.Domain.Visits.Visit", null)
                        .WithMany("Samples")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_samples_visits_visit_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.VisitTest", b =>
                {
                    b.HasOne("SkyLIS.Domain.Visits.Visit", null)
                        .WithMany("Tests")
                        .HasForeignKey("visit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_visit_tests_visits_visit_id");

                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("VisitTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("VisitTestId");

                            b1.ToTable("visit_tests", "visits");

                            b1.WithOwner()
                                .HasForeignKey("VisitTestId")
                                .HasConstraintName("fk_visit_tests_visit_tests_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.Panel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleType", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("SkyLIS.Domain.Org.Branch", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("SkyLIS.Domain.Reports.LabReport", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("SkyLIS.Domain.Results.TestResult", b =>
                {
                    b.Navigation("Critical");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Visit", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
