// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyLIS.Infrastructure.Persistence;

#nullable disable

namespace SkyLIS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SkyLisDbContext))]
    partial class SkyLisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyLIS.Domain.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("TenantId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_tenant_id_invoice_number");

                    b.HasIndex("TenantId", "VisitId")
                        .HasDatabaseName("ix_invoices_tenant_id_visit_id");

                    b.ToTable("invoices", "billing");
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("invoice_id")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("invoice_id")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.ToTable("payments", "billing");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.LabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<Guid?>("RequiredConditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_condition_id");

                    b.Property<Guid>("SampleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_lab_tests");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_tests_tenant_id_code");

                    b.ToTable("lab_tests", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompatibilityGroup")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("compatibility_group");

                    b.Property<int?>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("SampleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_type_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sample_conditions");

                    b.HasIndex("SampleTypeId")
                        .HasDatabaseName("ix_sample_conditions_sample_type_id");

                    b.ToTable("sample_conditions", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sample_types");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sample_types_tenant_id_name");

                    b.ToTable("sample_types", "catalog");
                });

            modelBuilder.Entity("SkyLIS.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confidential");

                    b.Property<DateTimeOffset?>("LastVisitAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit_at_utc");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("NationalId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("national_id");

                    b.Property<string>("PatientNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("patient_number");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("TenantId", "FullName")
                        .HasDatabaseName("ix_patients_tenant_id_full_name");

                    b.HasIndex("TenantId", "Mobile")
                        .HasDatabaseName("ix_patients_tenant_id_mobile");

                    b.HasIndex("TenantId", "NationalId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_tenant_id_national_id")
                        .HasFilter("national_id IS NOT NULL");

                    b.HasIndex("TenantId", "PatientNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_tenant_id_patient_number");

                    b.ToTable("patients", "patients");
                });

            modelBuilder.Entity("SkyLIS.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IsolationTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("isolation_tier");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("subdomain");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_subdomain");

                    b.ToTable("tenants", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset?>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at_utc");

                    b.Property<bool>("ConditionDelayed")
                        .HasColumnType("boolean")
                        .HasColumnName("condition_delayed");

                    b.Property<string>("ConditionName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("condition_name");

                    b.Property<DateTimeOffset?>("ConditionReadyAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("condition_ready_at_utc");

                    b.Property<DateTimeOffset?>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("rejection_reason_code");

                    b.Property<Guid>("SampleTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_type_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_samples");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_samples_visit_id");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_samples_tenant_id_barcode");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("ix_samples_tenant_id_state");

                    b.ToTable("samples", "visits");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsStat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stat");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("StatReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stat_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VisitNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("visit_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_visits_tenant_id_status");

                    b.HasIndex("TenantId", "VisitNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_visits_tenant_id_visit_number");

                    b.ToTable("visits", "visits");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.VisitTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sample_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("test_code");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid?>("visit_id")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_tests");

                    b.HasIndex("visit_id")
                        .HasDatabaseName("ix_visit_tests_visit_id");

                    b.ToTable("visit_tests", "visits");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", "outbox");
                });

            modelBuilder.Entity("SkyLIS.Infrastructure.Persistence.NumberSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_number_series");

                    b.HasIndex("TenantId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_number_series_tenant_id_kind");

                    b.ToTable("number_series", "platform");
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Invoice", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_currency");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("invoices", "billing");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_invoices_invoices_id");
                        });

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Payment", b =>
                {
                    b.HasOne("SkyLIS.Domain.Billing.Invoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("invoice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments", "billing");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId")
                                .HasConstraintName("fk_payments_payments_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.LabTest", b =>
                {
                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("LabTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("LabTestId");

                            b1.ToTable("lab_tests", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("LabTestId")
                                .HasConstraintName("fk_lab_tests_lab_tests_id");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleCondition", b =>
                {
                    b.HasOne("SkyLIS.Domain.Catalog.SampleType", null)
                        .WithMany("Conditions")
                        .HasForeignKey("SampleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sample_conditions_sample_types_sample_type_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Sample", b =>
                {
                    b.HasOne("SkyLIS.Domain.Visits.Visit", null)
                        .WithMany("Samples")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_samples_visits_visit_id");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.VisitTest", b =>
                {
                    b.HasOne("SkyLIS.Domain.Visits.Visit", null)
                        .WithMany("Tests")
                        .HasForeignKey("visit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_visit_tests_visits_visit_id");

                    b.OwnsOne("SkyLIS.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("VisitTestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("VisitTestId");

                            b1.ToTable("visit_tests", "visits");

                            b1.WithOwner()
                                .HasForeignKey("VisitTestId")
                                .HasConstraintName("fk_visit_tests_visit_tests_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("SkyLIS.Domain.Billing.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SkyLIS.Domain.Catalog.SampleType", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("SkyLIS.Domain.Visits.Visit", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
